# http://www.htpcguides.com/spin-down-and-manage-hard-drive-power-on-raspberry-pi/

- name: get currently installed hd-idle version
  shell: "dpkg-query --showformat='${Version}' --show hd-idle || true"
  register: hd_idle_detected_version
  ignore_errors: True
  changed_when: False

- name: "install compilation and support packages for hd_idle"
  apt: >
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=28800
  with_items:
    - build-essential
    - fakeroot
    - debhelper
  when: hd_idle_detected_version.stdout != "{{ hd_idle_version }}"

#- debug: var=hd_idle_detected_version

- name: "compile dir"
  file: path={{ hd_idle_compile_dir }} state=directory
  when: hd_idle_detected_version.stdout != "{{ hd_idle_version }}"

- name: Download hd-idle source
  get_url:
    url: "{{ hd_idle_url }}"
    dest: "{{ hd_idle_compile_dir }}/hd-idle-{{ hd_idle_version }}.tgz"
    checksum: "{{ hd_idle_checksum }}"
    validate_certs: False # we validate the checksum and stay compatible with old python versions
  when: hd_idle_detected_version.stdout != "{{ hd_idle_version }}"

- name: Unpack hd-idle source
  unarchive:
    src="{{ hd_idle_compile_dir }}/hd-idle-{{ hd_idle_version }}.tgz"
    dest={{ hd_idle_compile_dir }}
    creates={{ hd_idle_compile_dir }}/hd-idle
    copy=no
  when: hd_idle_detected_version.stdout != "{{ hd_idle_version }}"

- name: Compile hd-idle source
  command: chdir={{ hd_idle_compile_dir }}/hd-idle {{ item }}
  with_items:
    - dpkg-buildpackage -rfakeroot
  when: hd_idle_detected_version.stdout != "{{ hd_idle_version }}"

- name: Install hd-idle
  shell: chdir={{ hd_idle_compile_dir }} {{ item }}
  with_items:
    - "dpkg -i hd-idle_{{ hd_idle_version }}_*.deb" # wildcard ignores platform part, causes shell above
  when: hd_idle_detected_version.stdout != "{{ hd_idle_version }}"
  tags:
    - skip_ansible_lint

- name: "enable default startup of hd-idle"
  lineinfile:
    dest: /etc/default/hd-idle
    create: yes
    state: present
    line: "START_HD_IDLE=true"
    regexp: "^START_HD_IDLE="
  notify: "restart hd-idle"

- name: "set default options of hd-idle"
  lineinfile:
    dest: /etc/default/hd-idle
    create: yes
    state: present
    line: 'HD_IDLE_OPTS="-i 900 -l /var/log/hd-idle.log"'
    regexp: "^HD_IDLE_OPTS="
  notify: "restart hd-idle"

- name: restart hd-idle
  service: name=hd-idle state=restarted enabled=yes
  when: hd_idle_detected_version.stdout != "{{ hd_idle_version }}"
