---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: debian-buster-10
    box: bento/debian-10
    memory: 512
  - name: debian-stretch-9
    box: bento/debian-9
    memory: 512
  - name: debian-jessie-8
    box: bento/debian-8
    memory: 512
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
