---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: debian-buster-10
    box: aalmenar/debian-10  # TODO: switch to bento when released
    memory: 512
  - name: debian-stretch-9
    box: bento/debian-9
    memory: 512
  - name: debian-jessie-8
    box: bento/debian-8
    memory: 512
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
